# IN 절 이용
SELECT CART_ID
FROM CART_PRODUCTS
WHERE NAME='Yogurt'
    AND CART_ID
        IN (SELECT CART_ID
            FROM CART_PRODUCTS
            WHERE NAME='Milk')
ORDER BY CART_ID;

# CART_PRODUCTS 2개 이용
SELECT A.CART_ID
FROM CART_PRODUCTS A, CART_PRODUCTS B
WHERE A.CART_ID = B.CART_ID 
    AND (A.NAME = 'Yogurt' AND B.NAME = 'MILK')
ORDER BY A.CART_ID;